# Build APKs for all games using Capacitor
# Prerequisites: Android Studio + Android SDK installed
# Run: .\build-all.ps1

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$buildDir = $PSScriptRoot

# Game definitions: source HTML, app name, package ID
$games = @(
    @{ id = '2048'; src = '2048/2048m.html'; name = '2048'; pkg = 'com.matziq.g2048' },
    @{ id = 'bee'; src = 'bee/beem.html'; name = 'Bee'; pkg = 'com.matziq.bee' },
    @{ id = 'betris'; src = 'betris/betrism.html'; name = 'Betris'; pkg = 'com.matziq.betris' },
    @{ id = 'blood_joust'; src = 'blood_joust/blood_joustm.html'; name = 'Blood Joust'; pkg = 'com.matziq.bloodjoust' },
    @{ id = 'domino_combo'; src = 'domino_combo/indexm.html'; name = 'Domino Combo'; pkg = 'com.matziq.dominocombo' },
    @{ id = 'fruitpile'; src = 'fruitpile/fruitpilem.html'; name = 'FruitPile'; pkg = 'com.matziq.fruitpile' },
    @{ id = 'geodes'; src = 'geodes/geodesm.html'; name = 'Geodes'; pkg = 'com.matziq.geodes' },
    @{ id = 'real_or_ai'; src = 'real_or_ai/real_or_aim.html'; name = 'Real or AI'; pkg = 'com.matziq.realorai' },
    @{ id = 'treasure_aztecs'; src = 'treasure_aztecs/treasure_aztecsm.html'; name = 'Treasure Aztecs'; pkg = 'com.matziq.treasureaztecs' },
    @{ id = 'aztec_hero'; src = 'aztec_hero/indexm.html'; name = 'Aztec Hero'; pkg = 'com.matziq.aztechero' }
)

foreach ($game in $games) {
    $projDir = Join-Path $buildDir $game.id
    $wwwDir = Join-Path $projDir 'www'

    Write-Host "`n=== Building $($game.name) ===" -ForegroundColor Cyan

    # Create project directory
    if (!(Test-Path $projDir)) {
        New-Item -ItemType Directory -Path $projDir -Force | Out-Null
    }

    # Create www directory and copy game files
    if (!(Test-Path $wwwDir)) {
        New-Item -ItemType Directory -Path $wwwDir -Force | Out-Null
    }

    # Copy the game HTML as index.html
    $srcPath = Join-Path $root $game.src
    Copy-Item $srcPath (Join-Path $wwwDir 'index.html') -Force

    # Copy shared scripts (github-scores.js etc.) if referenced
    $scriptsDir = Join-Path $wwwDir 'scripts'
    if (!(Test-Path $scriptsDir)) {
        New-Item -ItemType Directory -Path $scriptsDir -Force | Out-Null
    }
    $srcScripts = Join-Path $root 'scripts'
    if (Test-Path $srcScripts) {
        Copy-Item "$srcScripts\github-scores.js" $scriptsDir -Force -ErrorAction SilentlyContinue
    }

    # For Real or AI, copy images and manifest
    if ($game.id -eq 'real_or_ai') {
        $aiDir = Join-Path $wwwDir 'ai'
        $realDir = Join-Path $wwwDir 'real'
        New-Item -ItemType Directory -Path $aiDir -Force | Out-Null
        New-Item -ItemType Directory -Path $realDir -Force | Out-Null
        Copy-Item (Join-Path $root 'real_or_ai\ai\*') $aiDir -Force -ErrorAction SilentlyContinue
        Copy-Item (Join-Path $root 'real_or_ai\real\*') $realDir -Force -ErrorAction SilentlyContinue
        Copy-Item (Join-Path $root 'real_or_ai\image_manifest.js') $wwwDir -Force -ErrorAction SilentlyContinue
    }

    # Create package.json
    $pkgJson = @{
        name    = $game.id
        version = '1.0.0'
        private = $true
    } | ConvertTo-Json
    Set-Content (Join-Path $projDir 'package.json') $pkgJson

    # Create capacitor.config.json
    $capConfig = @{
        appId   = $game.pkg
        appName = $game.name
        webDir  = 'www'
        server  = @{
            androidScheme = 'https'
        }
    } | ConvertTo-Json -Depth 3
    Set-Content (Join-Path $projDir 'capacitor.config.json') $capConfig

    # Copy node_modules from parent (shared Capacitor install)
    $nmSrc = Join-Path $buildDir 'node_modules'
    $nmDst = Join-Path $projDir 'node_modules'
    if (!(Test-Path $nmDst)) {
        # Use junction for speed (avoids copying hundreds of MB)
        cmd /c mklink /J "$nmDst" "$nmSrc" 2>&1 | Out-Null
    }

    # Add Android platform
    Push-Location $projDir
    try {
        if (!(Test-Path 'android')) {
            Write-Host "  Adding Android platform..."
            npx cap add android 2>&1 | Select-Object -Last 2
        }
        Write-Host "  Syncing web assets..."
        npx cap sync android 2>&1 | Select-Object -Last 2

        # Fix capacitor.settings.gradle path (junction-safe relative path)
        $capSettings = Join-Path $projDir 'android\capacitor.settings.gradle'
        @"
// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN
include ':capacitor-android'
project(':capacitor-android').projectDir = new File('../node_modules/@capacitor/android/capacitor')
"@ | Set-Content $capSettings -Encoding UTF8

        Write-Host "  Done: $($game.name)" -ForegroundColor Green
    }
    catch {
        Write-Host "  ERROR: $_" -ForegroundColor Red
    }
    Pop-Location
}

Write-Host "`n=== All projects ready ===" -ForegroundColor Green
Write-Host "To build APKs, install Android Studio, then for each game run:"
Write-Host "  cd apk_builds\<game_id>"
Write-Host "  npx cap open android"
Write-Host "Or build from command line (requires ANDROID_HOME set):"
Write-Host "  cd apk_builds\<game_id>\android"
Write-Host "  .\gradlew.bat assembleDebug"
Write-Host "APK will be at: android\app\build\outputs\apk\debug\app-debug.apk"
